// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcTb1T-978RglNIBCqUv7RNlkoImJ9fgY',
    appId: '1:715901211386:web:178e75a4469f45945eef43',
    messagingSenderId: '715901211386',
    projectId: 'myretagapp',
    authDomain: 'myretagapp.firebaseapp.com',
    storageBucket: 'myretagapp.firebasestorage.app',
    measurementId: 'G-YBRDHZ1108',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUy7Rsy9eE4vr2l0TROQ3rKSgJ1nlpZPc',
    appId: '1:715901211386:android:2a0c378d2d0589e55eef43',
    messagingSenderId: '715901211386',
    projectId: 'myretagapp',
    storageBucket: 'myretagapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_qkH8Wxg40IN3OmHyBDVG3SP1QWjaGQI',
    appId: '1:715901211386:ios:e05696f334a52c315eef43',
    messagingSenderId: '715901211386',
    projectId: 'myretagapp',
    storageBucket: 'myretagapp.firebasestorage.app',
    iosBundleId: 'com.example.retagApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_qkH8Wxg40IN3OmHyBDVG3SP1QWjaGQI',
    appId: '1:715901211386:ios:e05696f334a52c315eef43',
    messagingSenderId: '715901211386',
    projectId: 'myretagapp',
    storageBucket: 'myretagapp.firebasestorage.app',
    iosBundleId: 'com.example.retagApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcTb1T-978RglNIBCqUv7RNlkoImJ9fgY',
    appId: '1:715901211386:web:423c32bfae075ef55eef43',
    messagingSenderId: '715901211386',
    projectId: 'myretagapp',
    authDomain: 'myretagapp.firebaseapp.com',
    storageBucket: 'myretagapp.firebasestorage.app',
    measurementId: 'G-Z3DY6KZQJ0',
  );

}